### ISSUE TITLE
03 -scoreboard - using javascript

### ISSUE THREAD

**Issue by CelesteSippel** [CelesteSippel/assignments#4]
# Score Board

For this assignment, you will be creating a simple interactive scoreboard for your favorite sport.

## Requirements

- Refer to this mockup to design your page:

![](https://github.com/suncoast-devs/handbook/blob/a2f0c05d3914a8f16611da03a18dbe92cd821a92/curriculum/fundamentals/modules/javascript/_old/assignments/assets/scoreboard.png?raw=true)

- Use the HTML and CSS [here](https://gist.github.com/mdewey/d331c0a449b8e53b4adc472ec0e5a1e8) to jump-start your project.
- A user should be able to update a score and the teams playing.

### Explorer Mode

- [x] Create a new project and implement the design using the given HTML & CSS.
- [x] Assign click events to the `update` buttons to update the corresponding values on the page. The score buttons should adjust the current score by a "hard-coded" value.
- [x] Deploy your site.

### Adventure Mode

- [ ] Implement a Quarter/Period Tracker that would be appropriate for the sport.
- [x] Add some styling to make it more presentable. Have fun with it.
- [x] Make the layout responsive.

### Epic Mode

- [ ] Add a Timer that counts down automatically and updates the period/quarter appropriately.
- [ ] Save/load the information to local storage.
- [ ] Add CSS to the winning teams score to indicate who is currently winning.
- [ ] Add anything else that your sport would have on its scoreboard (e.g. fouls, sacks, shots on goal, etc.).
- [ ] Improve the UX to help to make scorekeeping by your sport easier.

**Comment by CelesteSippel** [comment]
https://github.com/CelesteSippel/score-board-counter

**Comment by lizthrilla** [comment]
The only change I would make is to default the starting score to 0 either by hardcoding it on lines 23 and 41 in the HTML or with the counter in Javascript.

**Comment by CelesteSippel** [comment]
Your homework **03 -scoreboard - using javascript** was marked: **Meets Expectations**

![Get up and dance!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBSdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3323b129c4533d8a45339c345692fab77f9771ac/meets-1.gif)
> &ldquo;Get up and dance!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/61)**__
